version: '3.8'

services:
  youtube_downloader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
