version: '3.8'

services:
  youtube_downloader:
    image: python:3.10-slim  # Use the official Python slim image
    container_name: youtube_downloader
    working_dir: /app
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    volumes:
      - downloads:/app/downloads  # Persist downloads on the host machine
    command: >
      sh -c "
      git clone https://github.com/Emeraldfalco/YT-Video-Downloader-Thing.git . &&
      pip install --no-cache-dir -r requirements.txt &&
      python app.py
      "

volumes:
  downloads:
