version: '3.8'

services:
  youtube_downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube_downloader
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    volumes:
      - downloads:/app/downloads  # Persist downloads on the host machine
    environment:
      - FLASK_ENV=production

volumes:
  downloads:
